import { useCallback, useEffect, useMemo, useState } from "react";
import { request } from "../../shared/api";
import type { Category, State } from "../../shared/types";
import { Loading } from "../../shared/ui";

function TrashIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M10 11v6m4-6v6M5.5 7l1 13h11l1-13M9 7V4h6v3"/></svg>}
function CopyIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>}
export default function Dashboard({token,manage,create}:{token:string;manage:(c:Category)=>void;create:()=>void}){
 const [state,setState]=useState<State|null>(null),[mode,setMode]=useState<"grid"|"list">("grid"),[query,setQuery]=useState(""),[copied,setCopied]=useState<number|null>(null),[busy,setBusy]=useState(false),[actionError,setActionError]=useState("");
 const load=useCallback(()=>request<State>("/admin/state",token).then(setState),[token]);useEffect(()=>{void load()},[load]);
 const categories=useMemo(()=>(state?.categories||[]).filter(c=>(c.name+" "+c.slug).toLowerCase().includes(query.trim().toLowerCase())),[state,query]);
 if(!state)return <Loading/>;
 const endpoint=(c:Category)=>new URL("/api/categories/"+c.slug,window.location.origin).toString();
 async function copy(c:Category){await navigator.clipboard.writeText(endpoint(c));setCopied(c.id);window.setTimeout(()=>setCopied(x=>x===c.id?null:x),1600)}
 async function remove(c:Category){if(!confirm("\u201c"+c.name+"\u201d kategorisi ve i\u00e7indeki t\u00fcm veriler silinsin mi?"))return;setBusy(true);setActionError("");try{await request("/admin/categories/"+c.id,token,{method:"DELETE"});setState(s=>s?{...s,categories:s.categories.filter(x=>x.id!==c.id)}:s)}catch(e){setActionError((e as Error).message)}finally{setBusy(false)}}
 async function toggle(){setBusy(true);setActionError("");try{const enabled=!state!.enabled;await request("/admin/state",token,{method:"PATCH",body:JSON.stringify({enabled})});setState(s=>s?{...s,enabled}:s)}catch(e){setActionError((e as Error).message)}finally{setBusy(false)}}
 return <div className="dashboard-page">
 <section className="category-create-card dashboard-reveal"><div className="create-card-mark"><span>＋</span></div><div className="create-card-copy"><div className="eyebrow">YENİ VERİ KAYNAĞI</div><h2>Yeni kategori oluştur</h2><p>Tablonu oluştur, sütunlarını ve kayıtlarını yönetmeye başla.</p></div><button className="btn create-category-button" onClick={create}>Kategori oluştur <span>→</span></button></section>
 <section className="overview-banner dashboard-reveal"><div className="overview-copy"><div className="eyebrow">API Y&#214;NET&#304;M ALANI</div><h2>Kategorileriniz tek yerde</h2><p>Payla&#351;&#305;lan API verilerinizi g&#246;r&#252;nt&#252;leyin ve y&#246;netin.</p></div><div className="service-control"><span className={"service-indicator "+(state.enabled?"is-on":"is-off")}/><div><strong>{state.enabled?"Servis \u00e7al\u0131\u015f\u0131yor":"Servis duraklat\u0131ld\u0131"}</strong><small>Genel API durumu</small></div><button className={"switch "+(state.enabled?"on":"")} disabled={busy} onClick={()=>void toggle()}>{state.enabled?"Durdur":"Ba\u015flat"}</button></div></section>
 <div className="dashboard-stats dashboard-reveal"><div><span className="stat-mark">▦</span><span><small>Kategori</small><strong>{state.categories.length}</strong></span></div><div><span className="stat-mark success">●</span><span><small>Aktif kategori</small><strong>{state.categories.filter(x=>x.active).length}</strong></span></div><div><span className={"stat-mark "+(state.enabled?"success":"muted-mark")}>⌁</span><span><small>Servis durumu</small><strong>{state.enabled?"A\u00e7\u0131k":"Kapal\u0131"}</strong></span></div></div>
 <section className="category-section dashboard-reveal"><div className="category-toolbar"><div><div className="eyebrow">VER&#304; KAYNAKLARI</div><h2>Kategoriler</h2></div><div className="category-tools"><label className="category-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kategori ara"/></label><div className="view-switch"><button className={mode==="grid"?"selected":""} onClick={()=>setMode("grid")} title="Kart g&#246;r&#252;n&#252;m&#252;">▦</button><button className={mode==="list"?"selected":""} onClick={()=>setMode("list")} title="Liste g&#246;r&#252;n&#252;m&#252;">☷</button></div></div></div>
 {categories.length?mode==="grid"?<div className="category-grid">{categories.map((c,i)=><article className="category-card" key={c.id} style={{"--card-index":i} as React.CSSProperties}><div className="category-card-top"><span className="category-glyph">{ "{ }" }</span><span className={"category-status "+(c.active?"":"off")}><i/>{c.active?"Aktif":"Pasif"}</span><button className="icon-button delete-icon" onClick={()=>void remove(c)} title="Kategoriyi sil" aria-label={c.name+" kategorisini sil"} disabled={busy}><TrashIcon/></button></div><h3>{c.name}</h3><div className="endpoint-label">API U&#199; NOKTASI</div><button className="endpoint-copy" onClick={()=>void copy(c)} title="Kopyalamak i&#231;in t&#305;klay&#305;n"><code>{endpoint(c)}</code><span>{copied===c.id?"Kopyaland\u0131":<CopyIcon/>}</span></button><div className="category-card-footer"><span>JSON veri tablosu</span><button className="btn manage-button" onClick={()=>manage(c)}>Y&#246;net <span>→</span></button></div></article>)}</div>
 :<div className="table-wrap category-list-wrap"><table className="table category-list"><thead><tr><th>Kategori</th><th>API u&#231; noktas&#305;</th><th>Durum</th><th>&#304;&#351;lemler</th></tr></thead><tbody>{categories.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td><button className="endpoint-copy list-endpoint" onClick={()=>void copy(c)}><code>{endpoint(c)}</code><span>{copied===c.id?"Kopyaland\u0131":<CopyIcon/>}</span></button></td><td><span className={"category-status "+(c.active?"":"off")}><i/>{c.active?"Aktif":"Pasif"}</span></td><td className="list-actions"><button className="btn manage-button" onClick={()=>manage(c)}>Y&#246;net →</button><button className="icon-button delete-icon" onClick={()=>void remove(c)} title="Kategoriyi sil" aria-label="Kategoriyi sil" disabled={busy}><TrashIcon/></button></td></tr>)}</tbody></table></div>
 :<div className="empty category-empty"><span className="empty-icon">▦</span><h3>{query?"Eşleşen kategori yok":"Henüz kategori yok"}</h3><p>{query?"Arama ifadenizi değiştirip tekrar deneyin.":"İlk veri kategorinizi Yeni bölümünden oluşturabilirsiniz."}</p></div>}{actionError&&<div className="manager-error" role="alert">{actionError}</div>}</section></div>
}
