import { FormEvent, useEffect, useState } from 'react';
type View='dashboard'|'new'|'keys'|'media';
type Category={id:number;name:string;slug:string;active:boolean};
type State={enabled:boolean;categories:Category[];records:unknown[]};
type ApiKey={id:string;projectName:string;apiKey:string;active:boolean};
type Media={id:string;name:string;url:string;mimeType:string};
async function request<T>(path:string,token:string|null,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const res=await fetch(path,{...options,headers});const json=await res.json();if(!res.ok)throw new Error(json.message||'İstek başarısız');return json.data??json}
export default function App(){const[token,setToken]=useState(()=>localStorage.getItem('gtk_token'));const[view,setView]=useState<View>('dashboard');if(!token)return <Login onLogin={v=>{localStorage.setItem('gtk_token',v);setToken(v)}}/>;return <Layout view={view} setView={setView} logout={()=>{localStorage.removeItem('gtk_token');setToken(null)}}>{view==='dashboard'?<Dashboard token={token}/>:view==='new'?<NewApi token={token} done={()=>setView('dashboard')}/>:view==='keys'?<Keys token={token}/>:<MediaPage token={token}/>}</Layout>}
function Login({onLogin}:{onLogin:(v:string)=>void}){const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{const data=await request<{token:string}>('/auth/login',null,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});onLogin(data.token)}catch(x){setError((x as Error).message)}}return <div className="login-page"><form className="login-card" onSubmit={submit}><Logo/><h1>API Yönetim Merkezi</h1><p className="muted">Servislerinizi tek noktadan yönetin.</p><Field label="E-posta" name="email" type="email" defaultValue="admin@guzelteknoloji.com"/><Field label="Şifre" name="password" type="password"/><div className="error">{error}</div><button className="btn">Giriş yap</button></form></div>}
function Layout({view,setView,logout,children}:{view:View;setView:(v:View)=>void;logout:()=>void;children:React.ReactNode}){return <div className="layout"><aside className="sidebar"><Logo/><nav className="nav"><Nav id="dashboard" view={view} set={setView} icon="▦" label="Dashboard"/><Nav id="new" view={view} set={setView} icon="＋" label="Yeni" extra="new"/><Nav id="keys" view={view} set={setView} icon="⌁" label="API Keys"/><Nav id="media" view={view} set={setView} icon="▧" label="Media"/></nav><div className="sidebar-footer">api.guzelteknoloji.com<br/>Web Service Console</div></aside><main className="main"><header className="header"><div><div className="eyebrow">Web Service Console</div><h1>{({dashboard:'Dashboard',new:'Yeni API',keys:'API Keys',media:'Media'})[view]}</h1></div><button className="btn soft" onClick={logout}>Çıkış</button></header>{children}</main></div>}
function Dashboard({token}:{token:string}){const[state,setState]=useState<State|null>(null);const load=()=>request<State>('/admin/state',token).then(setState);useEffect(load,[token]);if(!state)return <div className="empty">Yükleniyor…</div>;return <><div className="actions spread"><span className={'badge '+(state.enabled?'':'off')}>● {state.enabled?'API aktif':'API kapalı'}</span><button className="btn soft" onClick={async()=>{await request('/admin/state',token,{method:'PATCH',body:JSON.stringify({enabled:!state.enabled})});load()}}>{state.enabled?'Servisi kapat':'Servisi aç'}</button></div><section className="cards">{state.categories.length?state.categories.map(c=><article className="card api-card" key={c.id}><div className="icon">{'{ }'}</div><h3>{c.name}</h3><code>/api/categories/{c.slug}</code><footer><span className={'badge '+(c.active?'':'off')}>{c.active?'Aktif':'Kapalı'}</span><button className="btn soft">Yönet</button></footer></article>):<div className="empty"><h3>Henüz API kategorisi yok</h3><p>Soldaki “Yeni” alanından ilk API kategorinizi oluşturun.</p></div>}</section></>}
function NewApi({token,done}:{token:string;done:()=>void}){const[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await request('/admin/categories',token,{method:'POST',body:JSON.stringify({name:f.get('name'),slug:f.get('slug')})});done()}catch(x){setError((x as Error).message)}}return <section className="panel"><div className="panel-head"><div><div className="eyebrow">API üretim alanı</div><h2>Yeni kategori oluştur</h2></div></div><form className="form-grid" onSubmit={submit}><Field label="Kategori adı" name="name" placeholder="Örn. Vergi Daireleri"/><Field label="Endpoint adresi" name="slug" placeholder="vergi-daireleri"/><div className="error">{error}</div><div><button className="btn">API kategorisini oluştur</button></div></form></section>}
function Keys({token}:{token:string}){const[rows,setRows]=useState<ApiKey[]>([]);const load=()=>request<ApiKey[]>('/admin/api-keys',token).then(setRows);useEffect(load,[token]);return <section className="panel"><div className="panel-head"><div><div className="eyebrow">Proje erişimleri</div><h2>Anahtarlar</h2></div><button className="btn" onClick={async()=>{const projectName=prompt('Proje adı');if(projectName){await request('/admin/api-keys',token,{method:'POST',body:JSON.stringify({projectName})});load()}}}>Yeni anahtar</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Proje</th><th>API Key</th><th>Durum</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.projectName}</b></td><td className="key">{x.apiKey}</td><td><span className={'badge '+(x.active?'':'off')}>{x.active?'Aktif':'Kapalı'}</span></td></tr>)}</tbody></table></div></section>}
function MediaPage({token}:{token:string}){const[rows,setRows]=useState<Media[]>([]);const load=()=>request<Media[]>('/admin/media',token).then(setRows);useEffect(load,[token]);return <section className="panel"><div className="panel-head"><div><div className="eyebrow">Dosya galerisi</div><h2>Yüklenen medyalar</h2></div><button className="btn" onClick={async()=>{const name=prompt('Dosya adı');const url=name&&prompt('Dosya URL adresi');if(name&&url){await request('/admin/media',token,{method:'POST',body:JSON.stringify({name,url,mimeType:'image'})});load()}}}>Medya ekle</button></div><div className="media-grid">{rows.map(x=><article className="card media" key={x.id}><img src={x.url} alt=""/><div className="media-body"><b>{x.name}</b><p className="muted">{x.mimeType}</p></div></article>)}</div></section>}
function Field(props:{label:string;name:string;type?:string;defaultValue?:string;placeholder?:string}){return <div className="field"><label>{props.label}</label><input className="input" required {...props}/></div>}
function Logo(){return <div className="logo">Güzel <i>Teknoloji</i></div>}
function Nav({id,view,set,icon,label,extra=''}:{id:View;view:View;set:(v:View)=>void;icon:string;label:string;extra?:string}){return <button className={(view===id?'active ':'')+extra} onClick={()=>set(id)}><span>{icon}</span><span>{label}</span></button>}
