import 'dotenv/config';
import express,{type Request,type Response,type NextFunction}from'express';
import cors from'cors';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import path from'node:path';import{randomUUID}from'node:crypto';import{fileURLToPath}from'node:url';
import nodemailer from'nodemailer';import{createHash,randomInt,timingSafeEqual}from'node:crypto';
import{readStore,writeStore,readLoginSettings,writeLoginSettings,type RecordItem}from'./store.js';import{initDb,listCategories,pool}from'./db.js';
const app=express(),port=Number(process.env.PORT||4010),secret=process.env.JWT_SECRET||'change-this-secret',adminEmail=process.env.ADMIN_EMAIL||'admin@guzelteknoloji.com',adminHash=bcrypt.hashSync(process.env.ADMIN_PASSWORD||'123456',10),root=path.dirname(fileURLToPath(import.meta.url));
app.use(cors({origin:true}));app.use(express.json({limit:'2mb'}));app.use(express.static(path.resolve(root,'../public')));
type AuthRequest=Request&{user?:{email:string}};
function auth(req:AuthRequest,res:Response,next:NextFunction){const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!token)return res.status(401).json({success:false,message:'Oturum gerekli'});try{req.user=jwt.verify(token,secret)as{email:string};next()}catch{return res.status(401).json({success:false,message:'Oturum süresi doldu'})}}
function publicGuard(_req:Request,res:Response,next:NextFunction){void readStore().then(s=>s.enabled?next():res.status(503).json({success:false,message:'API şu anda kapalı'})).catch(()=>res.status(500).json({success:false,message:'Veri deposu okunamadı'}))}
app.get('/health',async(_q,r)=>{const s=await readStore();r.json({success:true,enabled:s.enabled,service:'guzel-teknoloji-api'})});
app.post('/auth/login',async(q,r)=>{const email=String(q.body?.email||'').trim().toLowerCase(),password=String(q.body?.password||'');if(email!==adminEmail.toLowerCase()||!bcrypt.compareSync(password,adminHash))return r.status(401).json({success:false,message:'Kullanıcı adı veya şifre hatalı'});r.json({success:true,token:jwt.sign({email},secret,{expiresIn:'12h'})})});
app.get('/login/settings',async(_q,r)=>r.json({success:true,data:await readLoginSettings()}));
app.get('/admin/login-settings',auth,async(_q,r)=>r.json({success:true,data:await readLoginSettings()}));
app.patch('/admin/login-settings',auth,async(q,r)=>{
  const previous=await readLoginSettings();
  const theme=q.body?.theme===undefined?previous.theme:q.body.theme;
  const quickLoginEnabled=q.body?.quickLoginEnabled===undefined?previous.quickLoginEnabled:q.body.quickLoginEnabled;
  const imageUrl=q.body?.imageUrl===undefined?previous.imageUrl:q.body.imageUrl;
  if(theme!=='light'&&theme!=='dark')return r.status(400).json({success:false,message:'Geçerli bir tema seçin'});
  if(typeof quickLoginEnabled!=='boolean')return r.status(400).json({success:false,message:'Hızlı giriş seçeneği geçersiz'});
  if(typeof imageUrl!=='string'||imageUrl.length>1_800_000||!(imageUrl==='/login-character.jpg'||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/]+=*$/.test(imageUrl)))return r.status(400).json({success:false,message:'Görsel PNG, JPEG veya WebP olmalı ve 1.3 MB sınırını aşmamalı'});
  const data=await writeLoginSettings({theme,quickLoginEnabled,imageUrl});
  return r.json({success:true,data});
});
type LoginCode={hash:string;expiresAt:number;attempts:number;sentAt:number};const loginCodes=new Map<string,LoginCode>();
const hashLoginCode=(value:string)=>createHash('sha256').update(value).digest();
app.post('/auth/request-otp',async(q,r)=>{if(!(await readLoginSettings()).quickLoginEnabled)return r.status(403).json({success:false,message:'Hizli giris yonetici tarafindan kapatilmis'});const email=String(q.body?.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return r.status(400).json({success:false,message:'Geçerli bir e-posta adresi girin'});const host=process.env.SMTP_HOST?.trim(),user=process.env.SMTP_USER?.trim(),pass=(process.env.SMTP_PASS||'').replace(/\s+/g,'');if(!host||!user||!pass)return r.status(503).json({success:false,message:'Hızlı giriş için SMTP ayarları sunucuda yapılandırılmalı'});if(email!==adminEmail.toLowerCase())return r.json({success:true,message:'Bu adres yönetici hesabıysa doğrulama kodu gönderildi'});const previous=loginCodes.get(email);if(previous&&Date.now()-previous.sentAt<60_000)return r.status(429).json({success:false,message:'Yeni kod istemeden önce bir dakika bekleyin'});const code=String(randomInt(100000,1000000)),expiresAt=Date.now()+5*60_000;loginCodes.set(email,{hash:hashLoginCode(code).toString('hex'),expiresAt,attempts:0,sentAt:Date.now()});try{const port=Number(process.env.SMTP_PORT||587),transport=nodemailer.createTransport({host,port,secure:port===465,auth:{user,pass}});await transport.sendMail({from:process.env.SMTP_FROM?.trim()||user,to:adminEmail,subject:'Güzel Teknoloji giriş doğrulama kodu',text:`Yönetim paneli giriş kodunuz: ${code}\nKod 5 dakika boyunca geçerlidir.`,html:`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;padding:28px;color:#18263a"><h2>Giriş doğrulama kodu</h2><p>Yönetim paneline giriş için bu kodu kullanın:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px;color:#1768df;padding:16px 0">${code}</div><p>Bu kod 5 dakika boyunca geçerlidir. Bu isteği siz başlatmadıysanız e-postayı dikkate almayın.</p></div>`});r.json({success:true,message:'Doğrulama kodu e-posta adresinize gönderildi'})}catch(error){loginCodes.delete(email);console.error('SMTP login code send failed',error);r.status(502).json({success:false,message:'E-posta gönderilemedi. SMTP ayarlarını kontrol edin'})}});
app.post('/auth/verify-otp',async(q,r)=>{if(!(await readLoginSettings()).quickLoginEnabled)return r.status(403).json({success:false,message:'Hizli giris yonetici tarafindan kapatilmis'});const email=String(q.body?.email||'').trim().toLowerCase(),code=String(q.body?.code||'').trim(),challenge=loginCodes.get(email);if(!challenge||email!==adminEmail.toLowerCase()||Date.now()>challenge.expiresAt){loginCodes.delete(email);return r.status(401).json({success:false,message:'Kodun süresi dolmuş veya kod isteği bulunamadı'});}if(!/^\d{6}$/.test(code)){return r.status(400).json({success:false,message:'6 haneli doğrulama kodunu girin'});}challenge.attempts+=1;const expected=Buffer.from(challenge.hash,'hex'),provided=hashLoginCode(code);if(challenge.attempts>5){loginCodes.delete(email);return r.status(429).json({success:false,message:'Çok fazla hatalı deneme. Yeni kod isteyin'});}if(!timingSafeEqual(expected,provided))return r.status(401).json({success:false,message:'Doğrulama kodu hatalı'});loginCodes.delete(email);r.json({success:true,token:jwt.sign({email},secret,{expiresIn:'12h'})})});
app.get('/admin/state',auth,async(_q,r)=>r.json({success:true,data:await readStore()}));app.patch('/admin/state',auth,async(q,r)=>{const s=await readStore();if(typeof q.body?.enabled==='boolean')s.enabled=q.body.enabled;await writeStore(s);r.json({success:true,data:s})});

app.get('/admin/categories',auth,async(_q,r)=>r.json({success:true,data:await listCategories()}));
app.post('/admin/categories',auth,async(q,r)=>{const name=String(q.body?.name||'').trim(),slug=String(q.body?.slug||name).trim().toLowerCase().replace(/[^a-z0-9ğüşıöç]+/gi,'-').replace(/^-|-$/g,'');if(!name||!slug)return r.status(400).json({success:false,message:'Kategori adı gerekli'});try{await initDb();const[x]=await pool.query<any>(`INSERT INTO api_categories(name,slug,active)VALUES(?,?,1)`,[name,slug]);r.status(201).json({success:true,data:{id:x.insertId,name,slug,active:true}})}catch{return r.status(400).json({success:false,message:'Bu kategori veya adres zaten kullanılıyor'})}});
app.patch('/admin/categories/:id',auth,async(q,r)=>{await initDb();await pool.query(`UPDATE api_categories SET name=COALESCE(?,name),active=COALESCE(?,active) WHERE id=?`,[q.body?.name??null,typeof q.body?.active==='boolean'?Number(q.body.active):null,Number(q.params.id)]);r.json({success:true})});
app.delete('/admin/categories/:id',auth,async(q,r)=>{await initDb();await pool.query(`DELETE FROM api_categories WHERE id=?`,[Number(q.params.id)]);r.json({success:true})});
app.get('/admin/categories/:id/schema',auth,async(q,r)=>{await initDb();const id=Number(q.params.id),[cats]=await pool.query<any[]>(`SELECT id,name,slug,active FROM api_categories WHERE id=?`,[id]);if(!cats[0])return r.status(404).json({success:false,message:'Kategori bulunamadı'});const[columns]=await pool.query<any[]>(`SELECT id,name,field_type fieldType,position FROM api_category_columns WHERE category_id=? ORDER BY position,id`,[id]),[rows]=await pool.query<any[]>(`SELECT id,data,active,updated_at updatedAt FROM api_category_rows WHERE category_id=? ORDER BY updated_at DESC`,[id]);r.json({success:true,data:{category:{...cats[0],active:Boolean(cats[0].active)},columns,rows:rows.map(x=>({...x,active:Boolean(x.active),data:typeof x.data==='string'?JSON.parse(x.data):x.data}))}})});
app.post('/admin/categories/:id/columns',auth,async(q,r)=>{await initDb();const id=Number(q.params.id),name=String(q.body?.name||'').trim(),fieldType=String(q.body?.fieldType||'text');if(!name)return r.status(400).json({success:false,message:'Sütun adı gerekli'});const[p]=await pool.query<any[]>(`SELECT COALESCE(MAX(position),-1)+1 position FROM api_category_columns WHERE category_id=?`,[id]);try{const[x]=await pool.query<any>(`INSERT INTO api_category_columns(category_id,name,field_type,position)VALUES(?,?,?,?)`,[id,name,fieldType,p[0].position]);r.status(201).json({success:true,data:{id:x.insertId,name,fieldType}})}catch{return r.status(400).json({success:false,message:'Bu sütun zaten mevcut'})}});
app.delete('/admin/categories/:categoryId/columns/:columnId',auth,async(q,r)=>{await initDb();await pool.query(`DELETE FROM api_category_columns WHERE id=? AND category_id=?`,[Number(q.params.columnId),Number(q.params.categoryId)]);r.json({success:true})});
app.post('/admin/categories/:id/rows',auth,async(q,r)=>{await initDb();const id=randomUUID();await pool.query(`INSERT INTO api_category_rows(id,category_id,data,active)VALUES(?,?,?,?)`,[id,Number(q.params.id),JSON.stringify(q.body?.data||{}),q.body?.active===false?0:1]);r.status(201).json({success:true,data:{id}})});
app.patch('/admin/categories/:categoryId/rows/:rowId',auth,async(q,r)=>{await initDb();await pool.query(`UPDATE api_category_rows SET data=COALESCE(?,data),active=COALESCE(?,active) WHERE id=? AND category_id=?`,[q.body?.data===undefined?null:JSON.stringify(q.body.data),typeof q.body?.active==='boolean'?Number(q.body.active):null,q.params.rowId,Number(q.params.categoryId)]);r.json({success:true})});
app.delete('/admin/categories/:categoryId/rows/:rowId',auth,async(q,r)=>{await initDb();await pool.query(`DELETE FROM api_category_rows WHERE id=? AND category_id=?`,[q.params.rowId,Number(q.params.categoryId)]);r.json({success:true})});

app.get('/admin/api-keys',auth,async(_q,r)=>{await initDb();const[rows]=await pool.query<any[]>(`SELECT k.id,k.project_name projectName,k.api_key apiKey,k.active,k.created_at createdAt,COUNT(DISTINCT l.id) usageCount,COUNT(DISTINCT NULLIF(l.origin_host,'')) siteCount,GROUP_CONCAT(DISTINCT c.name SEPARATOR '||') categoryNames,GROUP_CONCAT(DISTINCT c.id) categoryIds FROM api_keys k LEFT JOIN api_key_categories kc ON kc.api_key_id=k.id LEFT JOIN api_categories c ON c.id=kc.category_id LEFT JOIN api_usage_logs l ON l.api_key_id=k.id GROUP BY k.id ORDER BY k.created_at DESC`);r.json({success:true,data:rows.map(x=>({...x,active:Boolean(x.active),usageCount:Number(x.usageCount),siteCount:Number(x.siteCount),categoryNames:x.categoryNames?String(x.categoryNames).split('||'):[],categoryIds:x.categoryIds?String(x.categoryIds).split(',').map(Number):[]}))})});
app.post('/admin/api-keys',auth,async(q,r)=>{const projectName=String(q.body?.projectName||'').trim(),categoryIds=Array.isArray(q.body?.categoryIds)?q.body.categoryIds.map(Number):[];if(!projectName)return r.status(400).json({success:false,message:'Proje adı gerekli'});if(!categoryIds.length)return r.status(400).json({success:false,message:'En az bir API kategorisi seçin'});await initDb();const item={id:randomUUID(),projectName,apiKey:`gtk_${randomUUID().replace(/-/g,'')}`,active:true},c=await pool.getConnection();try{await c.beginTransaction();await c.query(`INSERT INTO api_keys(id,project_name,api_key,active)VALUES(?,?,?,1)`,[item.id,item.projectName,item.apiKey]);for(const categoryId of categoryIds)await c.query(`INSERT INTO api_key_categories(api_key_id,category_id)VALUES(?,?)`,[item.id,categoryId]);await c.commit()}catch(e){await c.rollback();throw e}finally{c.release()}r.status(201).json({success:true,data:item})});
app.patch('/admin/api-keys/:id',auth,async(q,r)=>{await initDb();await pool.query(`UPDATE api_keys SET active=? WHERE id=?`,[Number(Boolean(q.body?.active)),q.params.id]);r.json({success:true})});app.delete('/admin/api-keys/:id',auth,async(q,r)=>{await initDb();await pool.query(`DELETE FROM api_keys WHERE id=?`,[q.params.id]);r.json({success:true})});

app.get('/admin/media',auth,async(_q,r)=>{await initDb();const[x]=await pool.query<any[]>(`SELECT id,name,url,mime_type mimeType,active FROM api_media ORDER BY created_at DESC`);r.json({success:true,data:x})});app.post('/admin/media',auth,async(q,r)=>{const name=String(q.body?.name||'').trim(),url=String(q.body?.url||'').trim();if(!name||!url)return r.status(400).json({success:false,message:'Dosya adı ve URL gerekli'});await initDb();const id=randomUUID();await pool.query(`INSERT INTO api_media(id,name,url,mime_type,active)VALUES(?,?,?,?,1)`,[id,name,url,String(q.body?.mimeType||'image')]);r.status(201).json({success:true,data:{id}})});app.delete('/admin/media/:id',auth,async(q,r)=>{await initDb();await pool.query(`DELETE FROM api_media WHERE id=?`,[q.params.id]);r.json({success:true})});

app.get('/api/records',publicGuard,async(_q,r)=>{const s=await readStore();r.json({success:true,data:s.records.filter(x=>x.active)})});app.get('/admin/records',auth,async(_q,r)=>r.json({success:true,data:(await readStore()).records}));app.post('/admin/records',auth,async(q,r)=>{const name=String(q.body?.name||'').trim(),value=String(q.body?.value||'').trim();if(!name||!value)return r.status(400).json({success:false,message:'Ad ve değer zorunludur'});const s=await readStore(),item:RecordItem={id:randomUUID(),categoryId:0,name,value,active:q.body?.active!==false,updatedAt:new Date().toISOString()};s.records.unshift(item);await writeStore(s);r.status(201).json({success:true,data:item})});
app.get('/api/categories/:slug',publicGuard,async(q,r)=>{await initDb();const[cats]=await pool.query<any[]>(`SELECT id,name,slug FROM api_categories WHERE slug=? AND active=1`,[q.params.slug]),cat=cats[0];if(!cat)return r.status(404).json({success:false,message:'Kategori bulunamadı'});const key=String(q.headers['x-api-key']||q.query.apiKey||''),[counts]=await pool.query<any[]>(`SELECT COUNT(*) count FROM api_keys`);if(Number(counts[0].count)>0){const[keys]=await pool.query<any[]>(`SELECT k.id FROM api_keys k JOIN api_key_categories kc ON kc.api_key_id=k.id WHERE k.api_key=? AND k.active=1 AND kc.category_id=?`,[key,cat.id]);if(!keys[0])return r.status(401).json({success:false,message:'Bu API için geçerli bir X-API-Key gerekli'});await pool.query(`INSERT INTO api_usage_logs(api_key_id,category_id,origin_host)VALUES(?,?,?)`,[keys[0].id,cat.id,String(q.headers.origin||q.headers.referer||q.headers.host||'').slice(0,255)])}const[columns]=await pool.query<any[]>(`SELECT id,name FROM api_category_columns WHERE category_id=? ORDER BY position,id`,[cat.id]),[rows]=await pool.query<any[]>(`SELECT id,data FROM api_category_rows WHERE category_id=? AND active=1 ORDER BY updated_at DESC`,[cat.id]);const data=rows.map(row=>{const values=typeof row.data==='string'?JSON.parse(row.data):row.data,result:Record<string,unknown>={id:row.id};for(const column of columns)result[column.name]=values[String(column.id)]??values[column.name];return result;});r.json({success:true,category:cat,data})});
app.get('/v1/:slug',publicGuard,async(q,r)=>{
  await initDb();
  const slug=String(q.params.slug).toLowerCase();
  const aliases:Record<string,string[]>={locations:['locations','lokasyonlar'],'tax-offices':['tax-offices','taxoffices','vergi-daireleri','vergidaireleri'],banks:['banks','bankalar'],bins:['bins','bin','bin-kayitlari']};
  let[cats]=await pool.query<any[]>(`SELECT id,name,slug FROM api_categories WHERE slug=? AND active=1 LIMIT 1`,[slug]);
  if(!cats[0]&&aliases[slug]){const candidates=aliases[slug],marks=candidates.map(()=>'?').join(',');[cats]=await pool.query<any[]>(`SELECT id,name,slug FROM api_categories WHERE active=1 AND (slug IN (${marks}) OR LOWER(name) IN (${marks})) LIMIT 1`,[...candidates,...candidates]);}
  const category=cats[0];if(!category)return r.status(404).json({success:false,message:'Kategori bulunamadı'});
  const key=String(q.headers['x-api-key']||q.query.apiKey||'');
  const[keys]=await pool.query<any[]>(`SELECT k.id FROM api_keys k JOIN api_key_categories kc ON kc.api_key_id=k.id WHERE k.api_key=? AND k.active=1 AND kc.category_id=? LIMIT 1`,[key,category.id]);
  if(!keys[0])return r.status(401).json({success:false,message:'Bu API için geçerli bir X-API-Key gerekli'});
  await pool.query(`INSERT INTO api_usage_logs(api_key_id,category_id,origin_host)VALUES(?,?,?)`,[keys[0].id,category.id,String(q.headers.origin||q.headers.referer||q.headers.host||'').slice(0,255)]);
  const[columns]=await pool.query<any[]>(`SELECT id,name FROM api_category_columns WHERE category_id=? ORDER BY position,id`,[category.id]),[rows]=await pool.query<any[]>(`SELECT id,data FROM api_category_rows WHERE category_id=? AND active=1 ORDER BY updated_at DESC`,[category.id]);
  const data=rows.map(row=>{const values=typeof row.data==='string'?JSON.parse(row.data):row.data,result:Record<string,unknown>={id:row.id};for(const column of columns)result[column.name]=values[String(column.id)]??values[column.name];return result;});
  r.json({success:true,category:{id:category.id,name:category.name,slug:category.slug},data});
});
const publicDir=path.resolve(root,'../public');app.get(/^(?!\/api|\/admin|\/auth).*/,(_q,r)=>r.sendFile(path.join(publicDir,'index.html')));app.listen(port,()=>console.log(`Güzel Teknoloji API http://localhost:${port}`));
